#!/usr/bin/env ruby -s

$:.unshift File.expand_path("..", __FILE__) # Set to the correct path

require "interactiveshell"
require "interpreter"
require "readline"


interpreter = Interpreter.new

if ARGV.first
  interpreter.eval File.read(file)
else
    InteractiveShell.run(interpreter)
end
