#!/usr/bin/env ruby -s

$:.unshift File.expand_path("..", __FILE__) # Set to the correct path

require "interpreter"
require "interactiveshell"
require "readline"



interpreter = Interpreter.new.eval($e)

if ARGV.first
  interpreter.eval File.read(file)
else
    InteractiveShell.run(interpreter)
end
